'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import { ChatAppProvider } from '../../Context/ChatAppContext';
import { NavBar } from '../../Components';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <ChatAppProvider>
            <NavBar />
            {children}
          </ChatAppProvider>
        </main>
      </body>
    </html>
  );
}
